apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-06-06T06:24:29Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "36999"
  uid: c3eeb899-ad92-4281-973f-2425f2c5cfca
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.99.135.250
  clusterIPs:
  - 10.99.135.250
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31895
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}